table_name: observations
main_dttm_col: obs_date_time
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: public
sql: 'SELECT * FROM observations     '
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: add3064b-ce12-4f90-b374-d297159afccf
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: obs_voided
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: visit_date_started
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: obs_date_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: visit_date_stopped
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: date_created
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_datetime
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_numeric
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: previous_version_obs_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: parent_obs_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_drug
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: obs_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: form_namespace_and_path
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: obs_void_reason
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_coded_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: accession_number
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: question_label
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_coded
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: creator_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: location_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_complex
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_modifier
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: patient_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: answer_text
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: question_mapping
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: obs_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: encounter_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: encounter_type
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: question_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: visit_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: visit_type
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: location
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: comments
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: 4e5f4045-a62d-4964-b719-58229a60e7fe
